# docker-compose.yml
version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - app-network

  server:
    build:
      context: ./server_go
      dockerfile: Dockerfile
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8181:81"
    depends_on:
      - server
      - client
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
